ufo_instructions = """
Ontologies: The Building Blocks of Knowledge

At its core, an ontology is a formal and explicit representation of knowledge within a specific domain. It provides a structured framework for understanding the concepts, relationships, and properties that exist within that domain. Think of it as a map that guides us through the intricate landscape of knowledge.

Key Components of an Ontology:

Concepts (or Classes): These are the fundamental building blocks representing the essential entities or ideas within a domain. In the gaming world, examples could be "Game," "Player," "Card," or "Action."
Relationships: These define how concepts connect and interact with each other. Examples include "plays," "owns," "is part of," or "triggers."
Properties (or Attributes): These describe specific characteristics of concepts. In our gaming example, properties could be "game genre," "player skill level," "card value," or "action cost."
Types of Ontologies:

Domain-Specific Ontologies: These focus on a particular field or area of interest, such as medicine, finance, or, as we've seen, gaming.
Foundational Ontologies: These provide a more general and abstract framework for representing knowledge, independent of any specific domain. They define fundamental concepts like "object," "event," "time," and "space," which can be applied across various domains.
Unified Foundational Ontology (UFO): A Universal Language for Knowledge

UFO is a foundational ontology proposed by Guizzardi, designed to serve as a common language for representing knowledge across diverse domains. It's like a Rosetta Stone that helps us translate and understand information from different fields.

UFO's Three Pillars:

UFO-A (Endurants): This pillar deals with entities that exist in time and have a stable identity. Examples include people, objects, and concepts.
UFO-B (Perdurants): This pillar focuses on processes and events that unfold over time. Think of actions, interactions, and changes.
UFO-C: This pillar is still under development but is expected to address additional aspects of knowledge representation.
OntoUML: The Visual Language of Ontologies

To make ontologies more accessible and visually intuitive, OntoUML provides a graphical notation based on the Unified Modeling Language (UML). It allows us to create diagrams that represent the concepts, relationships, and properties of an ontology in a clear and concise way.

Advantages of Using Ontologies and UFO:

Improved Communication: Ontologies create a shared vocabulary and understanding, facilitating communication across different fields and disciplines.
Enhanced Knowledge Representation: They provide a structured way to represent knowledge, making it easier to reason about, query, and infer new information.
Increased Interoperability: Ontologies enable data and systems to be more easily integrated and shared across different platforms and applications.
Foundation for Artificial Intelligence: They serve as a knowledge base for AI systems, allowing them to understand and reason about the world more effectively.
"""

stereotypes = """
Endurant Type Stereotypes:

Kind: Represents a fundamental, independent type of entity in the world. Kinds have distinct principles for what makes them unique (individuation), how they remain the same over time (identity), and how long they persist (persistence).
Examples: Person, Organization, Game
Collective: Denotes a type of entity that is composed of multiple parts, and these parts often play similar roles within the whole.
Examples: Occupational Group, Deck (of cards)
Quantity: Signifies a specific portion or amount of matter.
Example: Could be applied to resources in a game if they're quantifiable, like "Gold" (measured in units)
Quality: Represents a property of an entity that can be understood as a value within a certain range or spectrum.
Examples: QualidadeRegra, QualidadeMecânica, Game Balance, Enjoyment (if quantified)
Mode: Signifies a property of an entity that is not conceptualized as a value on a scale.
Examples: Border Station (a state of an office), Finalistico (a mode of operation)
Relator: Indicates an entity that establishes a connection or relationship between other entities.
Examples: Production, Payment, Purchase, Sale
Subkind: Represents a specialized or more specific type of kind, where the specialization is inherent and unchanging.
Examples: Administrative Organization, Land Development Technician, Geographic Indication, Bitterness (as a subkind of emotion)
Phase: Denotes a temporary or transient state of a kind, often with specific conditions for entering and exiting that phase.
Examples: Border Station, Finalistico, Service Station, Central Office
Role: Indicates a type of entity that is defined by its function or relationship to other entities. The conditions for fulfilling this role are contingent and can change.
Examples: Jogador, Allocated Office, Server, Allocated Department, Value Object (in a game context)
Non-Sortal Type Stereotypes:

Category: Represents a rigid type that defines essential properties shared by all its instances. The category itself doesn't have direct instances.
Examples: Actor, Structure, Occupational Structure
Phase-mixin: Denotes a non-rigid type that defines contingent (non-essential) properties that an instance can gain or lose over time.
Example: This might be used for a temporary power-up in a game that changes a character's abilities.
Mixin: Signifies a semi-rigid type that has properties essential to some instances and accidental (non-essential) to others.
Example: "Card" in a card game could be a mixin. Some properties are essential (it's part of a deck), but others (being played, being a trump card) are accidental.
Other Stereotypes:

Type: A general term for both endurant and perdurant types.
Event: Represents a specific occurrence that unfolds over time.
Examples: Gameplay, Player Elimination, Attack
Situation: Denotes a state of affairs or a set of circumstances that exists at a particular time.
Examples: Final da partida de videogame, Inicio da partida de videogame
"""

examples = "\n".join([
    "input: Controlled Situation",
    "output: {\"name\": \"Controlled Situation\", \"description\": \"A situation that is under control or management.\", \"inferred_stereotype\": \"situation\"},",
    "input: Threat Event",
    "output: {\"name\": \"Threat Event\", \"description\": \"An event that poses a threat or danger.\", \"inferred_stereotype\": \"event\"},",
    "input: Control Capability",
    "output: {\"name\": \"Control Capability\", \"description\": \"The ability or capacity to control or manage something.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Risk Event",
    "output: {\"name\": \"Risk Event\", \"description\": \"An event that has the potential to cause harm or loss.\", \"inferred_stereotype\": \"event\"},",
    "input: Risk Subject",
    "output: {\"name\": \"Risk Subject\", \"description\": \"An entity that is exposed to or affected by risk.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Protection Event",
    "output: {\"name\": \"Protection Event\", \"description\": \"An event that provides protection or safeguards against harm or loss.\", \"inferred_stereotype\": \"event\"},",
    "input: Intention Type",
    "output: {\"name\": \"Intention Type\", \"description\": \"A type or category of intention.\", \"inferred_stereotype\": \"type\"},",
    "input: Generic Intention",
    "output: {\"name\": \"Generic Intention\", \"description\": \"A general or broad intention without specific details.\", \"inferred_stereotype\": \"category\"},",
    "input: Threat Object",
    "output: {\"name\": \"Threat Object\", \"description\": \"An object that poses a threat or danger.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Causal Likelihood",
    "output: {\"name\": \"Causal Likelihood\", \"description\": \"The likelihood or probability of a cause-and-effect relationship.\", \"inferred_stereotype\": \"quality\"},",
    "input: Value",
    "output: {\"name\": \"Value\", \"description\": \"The worth, importance, or usefulness of something.\", \"inferred_stereotype\": \"quality\"},",
    "input: Value Event",
    "output: {\"name\": \"Value Event\", \"description\": \"An event that affects or relates to value.\", \"inferred_stereotype\": \"event\"},",
    "input: Impactful Outcome",
    "output: {\"name\": \"Impactful Outcome\", \"description\": \"An outcome that has a significant impact or effect.\", \"inferred_stereotype\": \"situation\"},",
    "input: Protection Trigger",
    "output: {\"name\": \"Protection Trigger\", \"description\": \"An event or condition that initiates or triggers protection measures.\", \"inferred_stereotype\": \"situation\"},",
    "input: Vulnerability",
    "output: {\"name\": \"Vulnerability\", \"description\": \"A weakness or flaw that can be exploited to cause harm or loss.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Value Object",
    "output: {\"name\": \"Value Object\", \"description\": \"An object that has value or is associated with value.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Threat Capability",
    "output: {\"name\": \"Threat Capability\", \"description\": \"The ability or capacity to pose a threat or danger.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Vulnerability Type",
    "output: {\"name\": \"Vulnerability Type\", \"description\": \"A type or category of vulnerability.\", \"inferred_stereotype\": \"type\"},",
    "input: Object at Risk",
    "output: {\"name\": \"Object at Risk\", \"description\": \"An object that is exposed to or at risk of harm or loss.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Value Ascription",
    "output: {\"name\": \"Value Ascription\", \"description\": \"The act of assigning or attributing value to something.\", \"inferred_stereotype\": \"relator\"},",
    "input: Triggering Likelihood",
    "output: {\"name\": \"Triggering Likelihood\", \"description\": \"The likelihood or probability of something triggering an event or outcome.\", \"inferred_stereotype\": \"quality\"},",
    "input: Attacker",
    "output: {\"name\": \"Attacker\", \"description\": \"An entity that initiates an attack or offensive action.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Value Assessor",
    "output: {\"name\": \"Value Assessor\", \"description\": \"An entity that assesses or evaluates value.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Loss Triggering Situation Type",
    "output: {\"name\": \"Loss Triggering Situation Type\", \"description\": \"A type or category of situation that can trigger a loss.\", \"inferred_stereotype\": \"type\"},",
    "input: Impact Event",
    "output: {\"name\": \"Impact Event\", \"description\": \"An event that causes or results in an impact.\", \"inferred_stereotype\": \"event\"},",
    "input: Risk Assessment",
    "output: {\"name\": \"Risk Assessment\", \"description\": \"The process of identifying, analyzing, and evaluating risks.\", \"inferred_stereotype\": \"relator\"},",
    "input: Security Designer",
    "output: {\"name\": \"Security Designer\", \"description\": \"An entity that designs or develops security measures or systems.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Control Event",
    "output: {\"name\": \"Control Event\", \"description\": \"An event that involves controlling or managing something.\", \"inferred_stereotype\": \"event\"},",
    "input: Value Enabler",
    "output: {\"name\": \"Value Enabler\", \"description\": \"An entity or factor that enables or facilitates the creation or realization of value.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Value Experience",
    "output: {\"name\": \"Value Experience\", \"description\": \"The experience or perception of value by an individual or entity.\", \"inferred_stereotype\": \"event\"},",
    "input: Event",
    "output: {\"name\": \"Event\", \"description\": \"An occurrence or happening that has a specific time and place.\", \"inferred_stereotype\": \"event\"},",
    "input: Loss Situation",
    "output: {\"name\": \"Loss Situation\", \"description\": \"A situation that involves or results in a loss.\", \"inferred_stereotype\": \"situation\"},",
    "input: Event Type",
    "output: {\"name\": \"Event Type\", \"description\": \"A type or category of event.\", \"inferred_stereotype\": \"type\"},",
    "input: Agent",
    "output: {\"name\": \"Agent\", \"description\": \"An entity that acts or has the capacity to act.\", \"inferred_stereotype\": \"category\"},",
    "input: Risk Assessor",
    "output: {\"name\": \"Risk Assessor\", \"description\": \"An entity that assesses or evaluates risk.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Trigger Event",
    "output: {\"name\": \"Trigger Event\", \"description\": \"An event that initiates or sets off a chain of events or actions.\", \"inferred_stereotype\": \"event\"},",
    "input: Threatening Situation",
    "output: {\"name\": \"Threatening Situation\", \"description\": \"A situation that poses a threat or danger.\", \"inferred_stereotype\": \"situation\"},",
    "input: Risk",
    "output: {\"name\": \"Risk\", \"description\": \"The possibility of loss or injury.\", \"inferred_stereotype\": \"quality\"},",
    "input: Controlled Situation Type",
    "output: {\"name\": \"Controlled Situation Type\", \"description\": \"A type or category of situation that is under control or management.\", \"inferred_stereotype\": \"type\"},",
    "input: Risk Enabler",
    "output: {\"name\": \"Risk Enabler\", \"description\": \"An entity or factor that enables or increases the likelihood of risk.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Situation Type",
    "output: {\"name\": \"Situation Type\", \"description\": \"A type or category of situation.\", \"inferred_stereotype\": \"type\"},",
    "input: Action",
    "output: {\"name\": \"Action\", \"description\": \"A physical movement or series of movements.\", \"inferred_stereotype\": \"event\"},",
    "input: Loss Event",
    "output: {\"name\": \"Loss Event\", \"description\": \"An event that results in a loss.\", \"inferred_stereotype\": \"event\"},",
    "input: Threatening Situation Type",
    "output: {\"name\": \"Threatening Situation Type\", \"description\": \"A type or category of situation that is threatening.\", \"inferred_stereotype\": \"type\"},",
    "input: Experience Risk Assesment",
    "output: {\"name\": \"Experience Risk Assesment\", \"description\": \"The assessment of risk based on experience.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Loss Event Type",
    "output: {\"name\": \"Loss Event Type\", \"description\": \"A type or category of event that results in a loss.\", \"inferred_stereotype\": \"type\"},",
    "input: Threat Event Type",
    "output: {\"name\": \"Threat Event Type\", \"description\": \"A type or category of event that is threatening.\", \"inferred_stereotype\": \"type\"},",
    "input: Risk Event Type",
    "output: {\"name\": \"Risk Event Type\", \"description\": \"A type or category of event that involves risk.\", \"inferred_stereotype\": \"type\"},",
    "input: Intention",
    "output: {\"name\": \"Intention\", \"description\": \"An aim or plan.\", \"inferred_stereotype\": \"category\"},",
    "input: Object Risk Assesment",
    "output: {\"name\": \"Object Risk Assesment\", \"description\": \"The assessment of risk associated with an object.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Disposition",
    "output: {\"name\": \"Disposition\", \"description\": \"A person's inherent qualities of mind and character.\", \"inferred_stereotype\": \"category\"},",
    "input: Threat Capability Type",
    "output: {\"name\": \"Threat Capability Type\", \"description\": \"A type or category of threat capability.\", \"inferred_stereotype\": \"type\"},",
    "input: Control Chain Event",
    "output: {\"name\": \"Control Chain Event\", \"description\": \"An event that is part of a chain of events that are designed to control or mitigate a risk.\", \"inferred_stereotype\": \"event\"},",
    "input: Risk Experience",
    "output: {\"name\": \"Risk Experience\", \"description\": \"The experience of being exposed to or affected by risk.\", \"inferred_stereotype\": \"event\"},",
    "input: Specific Intention",
    "output: {\"name\": \"Specific Intention\", \"description\": \"A specific or detailed intention.\", \"inferred_stereotype\": \"category\"},",
    "input: Experience Value Asc.",
    "output: {\"name\": \"Experience Value Asc.\", \"description\": \"The ascription of value based on experience.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Attack",
    "output: {\"name\": \"Attack\", \"description\": \"An aggressive action.\", \"inferred_stereotype\": \"event\"},",
    "input: Situation",
    "output: {\"name\": \"Situation\", \"description\": \"A set of circumstances in which one finds oneself.\", \"inferred_stereotype\": \"situation\"},",
    "input: Protected Subject",
    "output: {\"name\": \"Protected Subject\", \"description\": \"An entity that is protected or safeguarded from harm.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Control Event Type",
    "output: {\"name\": \"Control Event Type\", \"description\": \"A type or category of control event.\", \"inferred_stereotype\": \"type\"},",
    "input: Value Subject",
    "output: {\"name\": \"Value Subject\", \"description\": \"An entity that is the subject of a value judgment.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Security Mechanism",
    "output: {\"name\": \"Security Mechanism\", \"description\": \"A process, device, or method used to protect information or a system.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Object Value Asc.",
    "output: {\"name\": \"Object Value Asc.\", \"description\": \"The ascription of value to an object.\", \"inferred_stereotype\": \"subkind\"}",
    "input: Single Table Inheritance Mapping",
    "output: {\"name\": \"Single Table Inheritance Mapping\", \"description\": \"A way of mapping an inheritance hierarchy into a single table.\", \"inferred_stereotype\": \"relator\"},",
    "input: Entity Subclass",
    "output: {\"name\": \"Entity Subclass\", \"description\": \"A subclass in an entity inheritance hierarchy.\", \"inferred_stereotype\": \"role\"},",
    "input: Relationship Mapping",
    "output: {\"name\": \"Relationship Mapping\", \"description\": \"The mapping of a relationship between entities to a database table.\", \"inferred_stereotype\": \"relator\"},",
    "input: Relationship Association Table",
    "output: {\"name\": \"Relationship Association Table\", \"description\": \"A table used to represent a many-to-many relationship between entities.\", \"inferred_stereotype\": \"role\"},",
    "input: Mapped Primary Key",
    "output: {\"name\": \"Mapped Primary Key\", \"description\": \"A primary key in an entity table that is mapped to a column in a database table.\", \"inferred_stereotype\": \"role\"},",
    "input: Variable Mapping",
    "output: {\"name\": \"Variable Mapping\", \"description\": \"The mapping of a variable in an entity class to a column in a database table.\", \"inferred_stereotype\": \"relator\"},",
    "input: Many To One Relationship Mapping",
    "output: {\"name\": \"Many To One Relationship Mapping\", \"description\": \"A mapping of a many-to-one relationship between entities to a database table.\", \"inferred_stereotype\": \"relator\"},",
    "input: One To Many Relationship Mapping",
    "output: {\"name\": \"One To Many Relationship Mapping\", \"description\": \"A mapping of a one-to-many relationship between entities to a database table.\", \"inferred_stereotype\": \"relator\"},",
    "input: Extendable Class",
    "output: {\"name\": \"Extendable Class\", \"description\": \"A class that can be extended by subclasses.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Subclass",
    "output: {\"name\": \"Subclass\", \"description\": \"A class that is derived from another class.\", \"inferred_stereotype\": \"role\"},",
    "input: Table per Concrete Class Inheritance Mapping",
    "output: {\"name\": \"Table per Concrete Class Inheritance Mapping\", \"description\": \"A way of mapping an inheritance hierarchy into separate tables for each concrete class.\", \"inferred_stereotype\": \"relator\"},",
    "input: Entity Superclass",
    "output: {\"name\": \"Entity Superclass\", \"description\": \"A superclass in an entity inheritance hierarchy.\", \"inferred_stereotype\": \"role\"},",
    "input: Table",
    "output: {\"name\": \"Table\", \"description\": \"A database table.\", \"inferred_stereotype\": \"kind\"},",
    "input: Many to Many Relationship Mapping",
    "output: {\"name\": \"Many to Many Relationship Mapping\", \"description\": \"A mapping of a many-to-many relationship between entities to a database table.\", \"inferred_stereotype\": \"relator\"},",
    "input: Entity Class",
    "output: {\"name\": \"Entity Class\", \"description\": \"A class that represents an entity in a database.\", \"inferred_stereotype\": \"role\"},",
    "input: Instance Variable",
    "output: {\"name\": \"Instance Variable\", \"description\": \"A variable that is associated with an instance of a class.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Table per Class Inheritance Mapping",
    "output: {\"name\": \"Table per Class Inheritance Mapping\", \"description\": \"A way of mapping an inheritance hierarchy into separate tables for each class.\", \"inferred_stereotype\": \"relator\"},",
    "input: Spuerclass",
    "output: {\"name\": \"Spuerclass\", \"description\": \"A superclass in an inheritance hierarchy.\", \"inferred_stereotype\": \"role\"},",
    "input: Primary Key Mapping",
    "output: {\"name\": \"Primary Key Mapping\", \"description\": \"The mapping of a primary key in an entity class to a column in a database table.\", \"inferred_stereotype\": \"relator\"},",
    "input: Mapped Variable",
    "output: {\"name\": \"Mapped Variable\", \"description\": \"A variable in an entity class that is mapped to a column in a database table.\", \"inferred_stereotype\": \"role\"},",
    "input: Inheritance",
    "output: {\"name\": \"Inheritance\", \"description\": \"The relationship between a class and its superclass.\", \"inferred_stereotype\": \"relator\"},",
    "input: Mapped Foreign Key",
    "output: {\"name\": \"Mapped Foreign Key\", \"description\": \"A foreign key in an entity table that is mapped to a column in a database table.\", \"inferred_stereotype\": \"role\"},",
    "input: Nullability",
    "output: {\"name\": \"Nullability\", \"description\": \"The ability of a column to contain null values.\", \"inferred_stereotype\": \"quality\"},",
    "input: Single Entity Table",
    "output: {\"name\": \"Single Entity Table\", \"description\": \"A table that contains data for a single entity.\", \"inferred_stereotype\": \"role\"},",
    "input: Inheritance Mapping",
    "output: {\"name\": \"Inheritance Mapping\", \"description\": \"The mapping of an inheritance hierarchy to a database schema.\", \"inferred_stereotype\": \"relator\"},",
    "input: One To One Relationship Mapping",
    "output: {\"name\": \"One To One Relationship Mapping\", \"description\": \"A mapping of a one-to-one relationship between entities to a database table.\", \"inferred_stereotype\": \"relator\"},",
    "input: Entity Table",
    "output: {\"name\": \"Entity Table\", \"description\": \"A table that represents an entity in a database.\", \"inferred_stereotype\": \"role\"},",
    "input: Foreign Key Column",
    "output: {\"name\": \"Foreign Key Column\", \"description\": \"A column in a database table that refers to the primary key of another table.\", \"inferred_stereotype\": \"role\"},",
    "input: Multiple Entities Table",
    "output: {\"name\": \"Multiple Entities Table\", \"description\": \"A table that contains data for multiple entities.\", \"inferred_stereotype\": \"role\"},",
    "input: Class",
    "output: {\"name\": \"Class\", \"description\": \"A blueprint for creating objects.\", \"inferred_stereotype\": \"kind\"},",
    "input: Column",
    "output: {\"name\": \"Column\", \"description\": \"A vertical division of a table.\", \"inferred_stereotype\": \"kind\"},",
    "input: Primary Key Column",
    "output: {\"name\": \"Primary Key Column\", \"description\": \"A column in a database table that uniquely identifies each row in the table.\", \"inferred_stereotype\": \"role\"},",
    "input: Class Mapping",
    "output: {\"name\": \"Class Mapping\", \"description\": \"The mapping of a class to a database table.\", \"inferred_stereotype\": \"relator\"},",
    "input: Foreign Key Mapping",
    "output: {\"name\": \"Foreign Key Mapping\", \"description\": \"The mapping of a foreign key in a class to a column in a database table.\", \"inferred_stereotype\": \"relator\"}",
    "input: MedidaQualidadeMecânica",
    "output: {\"name\": \"MedidaQualidadeMec\\u00e2nica\", \"description\": \"A measure of the quality of the mechanics of a video game.\", \"inferred_stereotype\": \"datatype\"},",
    "input: QualidadeRegra",
    "output: {\"name\": \"QualidadeRegra\", \"description\": \"A quality of the rules of the game.\", \"inferred_stereotype\": \"quality\"},",
    "input: Pessoa",
    "output: {\"name\": \"Pessoa\", \"description\": \"A person.\", \"inferred_stereotype\": \"kind\"},",
    "input: Final da partidade de videogame",
    "output: {\"name\": \"Final da partidade de videogame\", \"description\": \"The end of a video game match.\", \"inferred_stereotype\": \"situation\"},",
    "input: Gameplay",
    "output: {\"name\": \"Gameplay\", \"description\": \"The experience of playing a video game.\", \"inferred_stereotype\": \"event\"},",
    "input: Jogador",
    "output: {\"name\": \"Jogador\", \"description\": \"A player in a video game.\", \"inferred_stereotype\": \"role\"},",
    "input: Jogo qua agente",
    "output: {\"name\": \"Jogo qua agente\", \"description\": \"A game as an agent.\", \"inferred_stereotype\": \"role\"},",
    "input: Regra",
    "output: {\"name\": \"Regra\", \"description\": \"The rules of the game.\", \"inferred_stereotype\": \"kind\"},",
    "input: QualidadeMecânica",
    "output: {\"name\": \"QualidadeMec\\u00e2nica\", \"description\": \"The quality of the mechanics of a video game.\", \"inferred_stereotype\": \"quality\"},",
    "input: QualidadeDesign",
    "output: {\"name\": \"QualidadeDesign\", \"description\": \"The quality of the design of a video game.\", \"inferred_stereotype\": \"quality\"},",
    "input: Inicio da partida de videogame",
    "output: {\"name\": \"Inicio da partida de videogame\", \"description\": \"The beginning of a video game match.\", \"inferred_stereotype\": \"situation\"},",
    "input: MedidaQualidadeRegra",
    "output: {\"name\": \"MedidaQualidadeRegra\", \"description\": \"A measure of the quality of the rules of the game.\", \"inferred_stereotype\": \"datatype\"},",
    "input: Jogabilidade",
    "output: {\"name\": \"Jogabilidade\", \"description\": \"The playability of a video game.\", \"inferred_stereotype\": \"quality\"},",
    "input: Jogo de Videogame (software)",
    "output: {\"name\": \"Jogo de Videogame (software)\", \"description\": \"A video game software.\", \"inferred_stereotype\": \"kind\"},",
    "input: Usabilidade",
    "output: {\"name\": \"Usabilidade\", \"description\": \"The usability of a video game.\", \"inferred_stereotype\": \"quality\"},",
    "input: Mecânica",
    "output: {\"name\": \"Mec\\u00e2nica\", \"description\": \"The mechanics of a video game.\", \"inferred_stereotype\": \"kind\"},",
    "input: Design",
    "output: {\"name\": \"Design\", \"description\": \"The design of a video game.\", \"inferred_stereotype\": \"kind\"},",
    "input: MedidaQualidadeDesign",
    "output: {\"name\": \"MedidaQualidadeDesign\", \"description\": \"A measure of the quality of the design of a video game.\", \"inferred_stereotype\": \"datatype\"},",
    "input: Jogar",
    "output: {\"name\": \"Jogar\", \"description\": \"The act of playing a video game.\", \"inferred_stereotype\": \"relator\"}",
    "input: Risk Assessor",
    "output: {\"name\": \"Risk Assessor\", \"description\": \"An entity that assesses or evaluates risk.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Value Assessor",
    "output: {\"name\": \"Value Assessor\", \"description\": \"An entity that assesses or evaluates value.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Threat Event",
    "output: {\"name\": \"Threat Event\", \"description\": \"An event that poses a threat or danger.\", \"inferred_stereotype\": \"event\"},",
    "input: Threat Agent",
    "output: {\"name\": \"Threat Agent\", \"description\": \"An agent that initiates a threat event.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Value Event",
    "output: {\"name\": \"Value Event\", \"description\": \"An event that affects or relates to value.\", \"inferred_stereotype\": \"event\"},",
    "input: Intention",
    "output: {\"name\": \"Intention\", \"description\": \"An aim or plan.\", \"inferred_stereotype\": \"category\"},",
    "input: Valuation",
    "output: {\"name\": \"Valuation\", \"description\": \"The process of determining the value of something.\", \"inferred_stereotype\": \"event\"},",
    "input: Risk",
    "output: {\"name\": \"Risk\", \"description\": \"The possibility of loss or injury.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Value Ascription",
    "output: {\"name\": \"Value Ascription\", \"description\": \"The act of assigning or attributing value to something.\", \"inferred_stereotype\": \"relator\"},",
    "input: Causal Likelihood",
    "output: {\"name\": \"Causal Likelihood\", \"description\": \"The likelihood or probability of a cause-and-effect relationship.\", \"inferred_stereotype\": \"quality\"},",
    "input: Relator",
    "output: {\"name\": \"Relator\", \"description\": \"A type of entity that relates two or more other entities.\", \"inferred_stereotype\": \"category\"},",
    "input: Trigger Event",
    "output: {\"name\": \"Trigger Event\", \"description\": \"An event that initiates or sets off a chain of events or actions.\", \"inferred_stereotype\": \"event\"},",
    "input: Loss Ascription",
    "output: {\"name\": \"Loss Ascription\", \"description\": \"The act of assigning or attributing a loss to something.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Vulnerability",
    "output: {\"name\": \"Vulnerability\", \"description\": \"A weakness or flaw that can be exploited to cause harm or loss.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Mode",
    "output: {\"name\": \"Mode\", \"description\": \"A way or manner in which something occurs or is experienced.\", \"inferred_stereotype\": \"category\"},",
    "input: Impact Event",
    "output: {\"name\": \"Impact Event\", \"description\": \"An event that has a significant impact or effect.\", \"inferred_stereotype\": \"event\"},",
    "input: Value Asc. Ex Post",
    "output: {\"name\": \"Value Asc. Ex Post\", \"description\": \"The ascription of value after an event or situation has occurred.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Experience Value Asc.",
    "output: {\"name\": \"Experience Value Asc.\", \"description\": \"The ascription of value based on experience.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Loss Event",
    "output: {\"name\": \"Loss Event\", \"description\": \"An event that results in a loss or damage.\", \"inferred_stereotype\": \"event\"},",
    "input: Value Asc. Ex Ante",
    "output: {\"name\": \"Value Asc. Ex Ante\", \"description\": \"The ascription of value before an event or situation has occurred.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Attack",
    "output: {\"name\": \"Attack\", \"description\": \"An intentional act to cause harm or damage.\", \"inferred_stereotype\": \"event\"},",
    "input: Disposition",
    "output: {\"name\": \"Disposition\", \"description\": \"A person's inherent qualities of mind and character.\", \"inferred_stereotype\": \"category\"},",
    "input: Object Risk Assess.",
    "output: {\"name\": \"Object Risk Assess.\", \"description\": \"The assessment of risk associated with an object.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Event Type",
    "output: {\"name\": \"Event Type\", \"description\": \"A type or category of event.\", \"inferred_stereotype\": \"type\"},",
    "input: Root Cause Event",
    "output: {\"name\": \"Root Cause Event\", \"description\": \"The fundamental cause of an event or situation.\", \"inferred_stereotype\": \"event\"},",
    "input: Substantial",
    "output: {\"name\": \"Substantial\", \"description\": \"Having a firm basis in reality and therefore important, meaningful, or considerable.\", \"inferred_stereotype\": \"category\"},",
    "input: Hazardous Situation",
    "output: {\"name\": \"Hazardous Situation\", \"description\": \"A situation that poses a risk of harm or danger.\", \"inferred_stereotype\": \"situation\"},",
    "input: Trope",
    "output: {\"name\": \"Trope\", \"description\": \"A significant or recurrent theme.\", \"inferred_stereotype\": \"category\"},",
    "input: Situation Type",
    "output: {\"name\": \"Situation Type\", \"description\": \"A type or category of situation.\", \"inferred_stereotype\": \"type\"},",
    "input: Gain Ascription",
    "output: {\"name\": \"Gain Ascription\", \"description\": \"The act of assigning or attributing a gain to something.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Likelihood",
    "output: {\"name\": \"Likelihood\", \"description\": \"The state or fact of something being likely; probability.\", \"inferred_stereotype\": \"category\"},",
    "input: Value",
    "output: {\"name\": \"Value\", \"description\": \"The importance, worth, or usefulness of something.\", \"inferred_stereotype\": \"quality\"},",
    "input: Risk Subject",
    "output: {\"name\": \"Risk Subject\", \"description\": \"An entity that is exposed to or affected by risk.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Capability",
    "output: {\"name\": \"Capability\", \"description\": \"The power or ability to do something.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Agent",
    "output: {\"name\": \"Agent\", \"description\": \"A being with the capacity to act.\", \"inferred_stereotype\": \"category\"},",
    "input: Object at Risk",
    "output: {\"name\": \"Object at Risk\", \"description\": \"An object that is exposed to or at risk of harm or loss.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Risk Experience",
    "output: {\"name\": \"Risk Experience\", \"description\": \"The experience of being exposed to or affected by risk.\", \"inferred_stereotype\": \"event\"},",
    "input: Value Subject",
    "output: {\"name\": \"Value Subject\", \"description\": \"An entity that is the subject of a value judgment.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Value Perception",
    "output: {\"name\": \"Value Perception\", \"description\": \"The process of becoming aware of something through the senses.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Value Experience",
    "output: {\"name\": \"Value Experience\", \"description\": \"The experience or perception of value by an individual or entity.\", \"inferred_stereotype\": \"event\"},",
    "input: Value Assertion",
    "output: {\"name\": \"Value Assertion\", \"description\": \"A statement or declaration of the value of something.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Object Value Asc.",
    "output: {\"name\": \"Object Value Asc.\", \"description\": \"The ascription of value to an object.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Risk Assessment",
    "output: {\"name\": \"Risk Assessment\", \"description\": \"The evaluation of the potential for loss or damage from a given threat.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Impactful Outcome",
    "output: {\"name\": \"Impactful Outcome\", \"description\": \"An outcome that has a significant impact or effect.\", \"inferred_stereotype\": \"situation\"},",
    "input: Loss Situation",
    "output: {\"name\": \"Loss Situation\", \"description\": \"A situation that involves or results in a loss.\", \"inferred_stereotype\": \"situation\"},",
    "input: Endurant",
    "output: {\"name\": \"Endurant\", \"description\": \"An entity that exists in time and has a stable identity.\", \"inferred_stereotype\": \"category\"},",
    "input: Opportunity Event",
    "output: {\"name\": \"Opportunity Event\", \"description\": \"An event that presents a chance for something favorable to happen.\", \"inferred_stereotype\": \"event\"},",
    "input: Mental Aspect",
    "output: {\"name\": \"Mental Aspect\", \"description\": \"A feature or quality of the mind.\", \"inferred_stereotype\": \"category\"},",
    "input: Gain Event",
    "output: {\"name\": \"Gain Event\", \"description\": \"An event that results in a gain or benefit.\", \"inferred_stereotype\": \"event\"},",
    "input: Value Enabler",
    "output: {\"name\": \"Value Enabler\", \"description\": \"An entity or factor that enables or facilitates the creation or realization of value.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Threat Capability",
    "output: {\"name\": \"Threat Capability\", \"description\": \"The ability or capacity to pose a threat or danger.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Triggering Likelihood",
    "output: {\"name\": \"Triggering Likelihood\", \"description\": \"The likelihood or probability of something triggering an event or outcome.\", \"inferred_stereotype\": \"quality\"},",
    "input: Value Asc. Component",
    "output: {\"name\": \"Value Asc. Component\", \"description\": \"A component of a value ascription.\", \"inferred_stereotype\": \"relator\"},",
    "input: Experience Risk Assessment",
    "output: {\"name\": \"Experience Risk Assessment\", \"description\": \"The assessment of risk based on experience.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Situation",
    "output: {\"name\": \"Situation\", \"description\": \"A set of circumstances in which one finds oneself.\", \"inferred_stereotype\": \"situation\"},",
    "input: Event",
    "output: {\"name\": \"Event\", \"description\": \"An occurrence or happening that has a specific time and place.\", \"inferred_stereotype\": \"event\"},",
    "input: Object",
    "output: {\"name\": \"Object\", \"description\": \"A material thing that can be seen and touched.\", \"inferred_stereotype\": \"category\"},",
    "input: Value Object",
    "output: {\"name\": \"Value Object\", \"description\": \"An object that has value or is associated with value.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Action",
    "output: {\"name\": \"Action\", \"description\": \"The fact or process of doing something, typically to achieve an aim.\", \"inferred_stereotype\": \"event\"},",
    "input: Risk Event",
    "output: {\"name\": \"Risk Event\", \"description\": \"An event that has the potential to cause harm or loss.\", \"inferred_stereotype\": \"event\"},",
    "input: Quality",
    "output: {\"name\": \"Quality\", \"description\": \"The standard of something as measured against other things of a similar kind; the degree of excellence of something.\", \"inferred_stereotype\": \"category\"},",
    "input: Risk Enabler",
    "output: {\"name\": \"Risk Enabler\", \"description\": \"An entity or factor that enables or increases the likelihood of risk.\", \"inferred_stereotype\": \"roleMixin\"}",
    "input: Threat Object",
    "output: {\"name\": \"Threat Object\", \"description\": \"An object that poses a threat or danger.\", \"inferred_stereotype\": \"roleMixin\"},",
    "input: Administrative Organization",
    "output: {\"name\": \"Administrative Organization\", \"description\": \"An organization that is responsible for the administration of a particular area or activity.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Structure",
    "output: {\"name\": \"Structure\", \"description\": \"The arrangement of and relations between the parts or elements of something complex.\", \"inferred_stereotype\": \"category\"},",
    "input: Section",
    "output: {\"name\": \"Section\", \"description\": \"A distinct part or subdivision of something.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Border Station",
    "output: {\"name\": \"Border Station\", \"description\": \"A station located at a border.\", \"inferred_stereotype\": \"phase\"},",
    "input: Natural Resources Technician",
    "output: {\"name\": \"Natural Resources Technician\", \"description\": \"A technician who works with natural resources.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Occupational Group",
    "output: {\"name\": \"Occupational Group\", \"description\": \"A group of people who share the same occupation.\", \"inferred_stereotype\": \"collective\"},",
    "input: Diagnostic Laboratory",
    "output: {\"name\": \"Diagnostic Laboratory\", \"description\": \"A laboratory where diagnoses are made.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Person",
    "output: {\"name\": \"Person\", \"description\": \"A human being.\", \"inferred_stereotype\": \"kind\"},",
    "input: Operational Organization",
    "output: {\"name\": \"Operational Organization\", \"description\": \"An organization that is responsible for the day-to-day operations of a particular area or activity.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Finalistico",
    "output: {\"name\": \"Finalistico\", \"description\": \"Having a definite purpose or goal.\", \"inferred_stereotype\": \"phase\"},",
    "input: Service Station",
    "output: {\"name\": \"Service Station\", \"description\": \"A place where services are provided.\", \"inferred_stereotype\": \"phase\"},",
    "input: Position",
    "output: {\"name\": \"Position\", \"description\": \"A job or post in an organization.\", \"inferred_stereotype\": \"kind\"},",
    "input: Central Office",
    "output: {\"name\": \"Central Office\", \"description\": \"The main office of an organization.\", \"inferred_stereotype\": \"phase\"},",
    "input: Land Development Technician",
    "output: {\"name\": \"Land Development Technician\", \"description\": \"A technician who works on land development projects.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Mobile Unit",
    "output: {\"name\": \"Mobile Unit\", \"description\": \"A unit that is capable of being moved.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Ancillary Service",
    "output: {\"name\": \"Ancillary Service\", \"description\": \"A service that is provided in addition to the main service.\", \"inferred_stereotype\": \"phase\"},",
    "input: Occupational Structure",
    "output: {\"name\": \"Occupational Structure\", \"description\": \"The structure of an occupation, including its hierarchy and the relationships between different positions.\", \"inferred_stereotype\": \"category\"},",
    "input: Allocated Office",
    "output: {\"name\": \"Allocated Office\", \"description\": \"An office that has been assigned to a particular person or department.\", \"inferred_stereotype\": \"role\"},",
    "input: Laboratory Technician",
    "output: {\"name\": \"Laboratory Technician\", \"description\": \"A technician who works in a laboratory.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Organization",
    "output: {\"name\": \"Organization\", \"description\": \"An organized group of people with a particular purpose, such as a business or government department.\", \"inferred_stereotype\": \"kind\"},",
    "input: Assignment",
    "output: {\"name\": \"Assignment\", \"description\": \"The allocation of someone or something as belonging to a particular group or category.\", \"inferred_stereotype\": \"relator\"},",
    "input: Regional Office",
    "output: {\"name\": \"Regional Office\", \"description\": \"An office that is responsible for a particular region.\", \"inferred_stereotype\": \"phase\"},",
    "input: Server Allocation",
    "output: {\"name\": \"Server Allocation\", \"description\": \"The allocation of a server to a particular task or function.\", \"inferred_stereotype\": \"relator\"},",
    "input: Cartography Technician",
    "output: {\"name\": \"Cartography Technician\", \"description\": \"A technician who creates maps.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Organizational Structure",
    "output: {\"name\": \"Organizational Structure\", \"description\": \"The hierarchical arrangement of lines of authority, communications, rights and duties of an organization.\", \"inferred_stereotype\": \"category\"},",
    "input: Occupied Position",
    "output: {\"name\": \"Occupied Position\", \"description\": \"A position that is currently filled by someone.\", \"inferred_stereotype\": \"role\"},",
    "input: Technical Department",
    "output: {\"name\": \"Technical Department\", \"description\": \"A department that is responsible for the technical aspects of an organization's work.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Technical Admnistrative Support",
    "output: {\"name\": \"Technical Admnistrative Support\", \"description\": \"Technical and administrative support.\", \"inferred_stereotype\": \"phase\"},",
    "input: Administrative Department",
    "output: {\"name\": \"Administrative Department\", \"description\": \"A department that is responsible for the administrative aspects of an organization's work.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Operational Structure",
    "output: {\"name\": \"Operational Structure\", \"description\": \"The structure of an organization's operations, including its processes and procedures.\", \"inferred_stereotype\": \"kind\"},",
    "input: Plant Health Inspector",
    "output: {\"name\": \"Plant Health Inspector\", \"description\": \"An inspector who checks plants for diseases and pests.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Advisory",
    "output: {\"name\": \"Advisory\", \"description\": \"Having or consisting in the power to make recommendations but not to take action enforcing them.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Department Allocation",
    "output: {\"name\": \"Department Allocation\", \"description\": \"The allocation of departments to different areas or functions.\", \"inferred_stereotype\": \"relator\"},",
    "input: Office",
    "output: {\"name\": \"Office\", \"description\": \"A room, set of rooms, or building used as a place for commercial, professional, or bureaucratic work.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Station",
    "output: {\"name\": \"Station\", \"description\": \"A regular stopping place on a public transport route.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Local Office",
    "output: {\"name\": \"Local Office\", \"description\": \"An office that serves a particular locality.\", \"inferred_stereotype\": \"phase\"},",
    "input: Board",
    "output: {\"name\": \"Board\", \"description\": \"A group of people constituted as the decision-making body of an organization.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Administrative Structure",
    "output: {\"name\": \"Administrative Structure\", \"description\": \"The structure of an organization's administration, including its hierarchy and the relationships between different positions.\", \"inferred_stereotype\": \"kind\"},",
    "input: Department",
    "output: {\"name\": \"Department\", \"description\": \"A division of a large organization dealing with a specific area of activity.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Allocation Unit",
    "output: {\"name\": \"Allocation Unit\", \"description\": \"A unit that is used for allocation.\", \"inferred_stereotype\": \"role\"}",
    "input: Allocated Department",
    "output: {\"name\": \"Allocated Department\", \"description\": \"A department that has been assigned to a particular area or function.\", \"inferred_stereotype\": \"role\"},",
    "input: Server",
    "output: {\"name\": \"Server\", \"description\": \"A computer or computer program that manages access to a centralized resource or service in a network.\", \"inferred_stereotype\": \"role\"},",
    "input: Animal Health Inspector",
    "output: {\"name\": \"Animal Health Inspector\", \"description\": \"An inspector who checks animals for diseases and pests.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Ancillary Server",
    "output: {\"name\": \"Ancillary Server\", \"description\": \"A server that provides additional support to a main server.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Technical Support",
    "output: {\"name\": \"Technical Support\", \"description\": \"Assistance with the use of technology products such as computers or software.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Administrative Support",
    "output: {\"name\": \"Administrative Support\", \"description\": \"Clerical services such as answering phones, typing, filing, and making travel arrangements.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Provenance",
    "output: {\"name\": \"Provenance\", \"description\": \"The place of origin or earliest known history of something.\", \"inferred_stereotype\": \"kind\"},",
    "input: Policy",
    "output: {\"name\": \"Policy\", \"description\": \"A course or principle of action adopted or proposed by a government, party, business, or individual.\", \"inferred_stereotype\": \"kind\"},",
    "input: Actor",
    "output: {\"name\": \"Actor\", \"description\": \"A person or thing that takes an active part in something.\", \"inferred_stereotype\": \"category\"},",
    "input: Production",
    "output: {\"name\": \"Production\", \"description\": \"The action of making or manufacturing from components or raw materials, or the process of being so manufactured.\", \"inferred_stereotype\": \"relator\"},",
    "input: Payment",
    "output: {\"name\": \"Payment\", \"description\": \"The action or process of paying someone or something, or of being paid.\", \"inferred_stereotype\": \"relator\"},",
    "input: Provider",
    "output: {\"name\": \"Provider\", \"description\": \"A person or thing that provides something.\", \"inferred_stereotype\": \"kind\"},",
    "input: ConsumerNeed",
    "output: {\"name\": \"ConsumerNeed\", \"description\": \"The need or desire of a consumer for a particular product or service.\", \"inferred_stereotype\": \"relator\"},",
    "input: Agent",
    "output: {\"name\": \"Agent\", \"description\": \"A person or thing that takes an active role or produces a specific effect.\", \"inferred_stereotype\": \"kind\"},",
    "input: Consumer",
    "output: {\"name\": \"Consumer\", \"description\": \"A person who purchases goods and services for personal use.\", \"inferred_stereotype\": \"kind\"},",
    "input: ProvenanceEvaluation",
    "output: {\"name\": \"ProvenanceEvaluation\", \"description\": \"The evaluation of the provenance of something.\", \"inferred_stereotype\": \"nonPerceivableQuality\"},",
    "input: Purchase",
    "output: {\"name\": \"Purchase\", \"description\": \"The action of buying something.\", \"inferred_stereotype\": \"relator\"},",
    "input: Receipt",
    "output: {\"name\": \"Receipt\", \"description\": \"The action of receiving something or the fact of its being received.\", \"inferred_stereotype\": \"relator\"},",
    "input: BusinessNeed",
    "output: {\"name\": \"BusinessNeed\", \"description\": \"A need or requirement of a business.\", \"inferred_stereotype\": \"kind\"},",
    "input: EndProduct",
    "output: {\"name\": \"EndProduct\", \"description\": \"The final product or result of a process.\", \"inferred_stereotype\": \"kind\"},",
    "input: DeclaredValue",
    "output: {\"name\": \"DeclaredValue\", \"description\": \"The value of something as declared by the owner or seller.\", \"inferred_stereotype\": \"stringNominalStructure\"},",
    "input: Sale",
    "output: {\"name\": \"Sale\", \"description\": \"The exchange of a commodity for money; the action of selling something.\", \"inferred_stereotype\": \"relator\"},",
    "input: GeographicIndication",
    "output: {\"name\": \"GeographicIndication\", \"description\": \"An indication that identifies a good as originating in a specific geographical location.\", \"inferred_stereotype\": \"subkind\"},",
    "input: DeclaredProvenance",
    "output: {\"name\": \"DeclaredProvenance\", \"description\": \"The provenance of something as declared by the owner or seller.\", \"inferred_stereotype\": \"subkind\"},",
    "input: ValueObject",
    "output: {\"name\": \"ValueObject\", \"description\": \"An object that has value or is associated with value.\", \"inferred_stereotype\": \"category\"},",
    "input: ValueActivity",
    "output: {\"name\": \"ValueActivity\", \"description\": \"An activity that creates or adds value.\", \"inferred_stereotype\": \"category\"},",
    "input: RawProduct",
    "output: {\"name\": \"RawProduct\", \"description\": \"A basic material from which a product is made.\", \"inferred_stereotype\": \"kind\"},",
    "input: CounterObject",
    "output: {\"name\": \"CounterObject\", \"description\": \"An object that is used to represent a value or quantity in a game.\", \"inferred_stereotype\": \"kind\"},",
    "input: Aversion",
    "output: {\"name\": \"Aversion\", \"description\": \"A strong dislike or disinclination.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Secret Unit Depoyment",
    "output: {\"name\": \"Secret Unit Depoyment\", \"description\": \"The deployment of a secret unit in a game.\", \"inferred_stereotype\": \"kind\"},",
    "input: Competition",
    "output: {\"name\": \"Competition\", \"description\": \"The activity or condition of competing.\", \"inferred_stereotype\": \"kind\"},",
    "input: Player Elimination",
    "output: {\"name\": \"Player Elimination\", \"description\": \"The elimination of a player from a game.\", \"inferred_stereotype\": \"kind\"},",
    "input: Game Balance",
    "output: {\"name\": \"Game Balance\", \"description\": \"The state of a game in which no one player or side has an unfair advantage.\", \"inferred_stereotype\": \"kind\"},",
    "input: Stock Holding",
    "output: {\"name\": \"Stock Holding\", \"description\": \"The act of holding or owning a stock or share in a company.\", \"inferred_stereotype\": \"kind\"},",
    "input: Betting",
    "output: {\"name\": \"Betting\", \"description\": \"The action of gambling money on the outcome of a race, game, or other unpredictable event.\", \"inferred_stereotype\": \"kind\"},",
    "input: Card",
    "output: {\"name\": \"Card\", \"description\": \"A piece of thick, stiff paper or thin cardboard, in particular one used for playing games or as a means of identification.\", \"inferred_stereotype\": \"kind\"},",
    "input: Bitterness",
    "output: {\"name\": \"Bitterness\", \"description\": \"A sharp, acrid taste or smell.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Trepidation",
    "output: {\"name\": \"Trepidation\", \"description\": \"A feeling of fear or agitation about something that may happen.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Bluffing",
    "output: {\"name\": \"Bluffing\", \"description\": \"The act of trying to deceive someone as to one's abilities or intentions.\", \"inferred_stereotype\": \"kind\"},",
    "input: Vengefulness",
    "output: {\"name\": \"Vengefulness\", \"description\": \"The desire for revenge.\", \"inferred_stereotype\": \"subkind\"}",
    "input: Pool Building",
    "output: {\"name\": \"Pool Building\", \"description\": \"The process of collecting or gathering resources in a game.\", \"inferred_stereotype\": \"kind\"},",
    "input: Anguish",
    "output: {\"name\": \"Anguish\", \"description\": \"A feeling of extreme mental distress or physical pain.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Token",
    "output: {\"name\": \"Token\", \"description\": \"A small object used to represent something else.\", \"inferred_stereotype\": \"kind\"},",
    "input: Fiero",
    "output: {\"name\": \"Fiero\", \"description\": \"A feeling of intense pride and accomplishment.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Algorithm",
    "output: {\"name\": \"Algorithm\", \"description\": \"A process or set of rules to be followed in calculations or other problem-solving operations, especially by a computer.\", \"inferred_stereotype\": \"kind\"},",
    "input: Despair",
    "output: {\"name\": \"Despair\", \"description\": \"The complete loss or absence of hope.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Sacrifice",
    "output: {\"name\": \"Sacrifice\", \"description\": \"An act of giving up something valued for the sake of something else regarded as more important or worthy.\", \"inferred_stereotype\": \"kind\"},",
    "input: Wonder",
    "output: {\"name\": \"Wonder\", \"description\": \"A feeling of amazement and admiration, caused by something beautiful, remarkable, or unfamiliar.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Point-toPointMovement",
    "output: {\"name\": \"Point-toPointMovement\", \"description\": \"A type of movement in which an object or character moves directly from one point to another.\", \"inferred_stereotype\": \"kind\"},",
    "input: Commodity Speculation",
    "output: {\"name\": \"Commodity Speculation\", \"description\": \"The act of trading in commodities in the hope of profit from changes in the market price.\", \"inferred_stereotype\": \"kind\"},",
    "input: Identification",
    "output: {\"name\": \"Identification\", \"description\": \"The action or process of identifying someone or something or the fact of being identified.\", \"inferred_stereotype\": \"kind\"},",
    "input: Diversion",
    "output: {\"name\": \"Diversion\", \"description\": \"An instance of turning something aside from its course.\", \"inferred_stereotype\": \"kind\"},",
    "input: Intimidate",
    "output: {\"name\": \"Intimidate\", \"description\": \"Frighten or overawe (someone), especially in order to make them do what one wants.\", \"inferred_stereotype\": \"kind\"},",
    "input: Acting",
    "output: {\"name\": \"Acting\", \"description\": \"The art or occupation of performing in plays, films, or television productions.\", \"inferred_stereotype\": \"kind\"},",
    "input: Reject objectives",
    "output: {\"name\": \"Reject objectives\", \"description\": \"The act of refusing to accept or agree with objectives.\", \"inferred_stereotype\": \"kind\"},",
    "input: Action Points",
    "output: {\"name\": \"Action Points\", \"description\": \"A unit of measurement used in some games to determine how many actions a character can take.\", \"inferred_stereotype\": \"kind\"},",
    "input: Variable Player Powers",
    "output: {\"name\": \"Variable Player Powers\", \"description\": \"The ability of players to have different powers in a game.\", \"inferred_stereotype\": \"kind\"},",
    "input: Enjoyment",
    "output: {\"name\": \"Enjoyment\", \"description\": \"The state or process of taking pleasure in something.\", \"inferred_stereotype\": \"kind\"},",
    "input: Alliance",
    "output: {\"name\": \"Alliance\", \"description\": \"A union or association formed for mutual benefit, especially between countries or organizations.\", \"inferred_stereotype\": \"kind\"},",
    "input: Movement",
    "output: {\"name\": \"Movement\", \"description\": \"An act of changing physical location or position or of having this changed.\", \"inferred_stereotype\": \"kind\"},",
    "input: Fury",
    "output: {\"name\": \"Fury\", \"description\": \"Wild or violent anger.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Action Draft",
    "output: {\"name\": \"Action Draft\", \"description\": \"A game mechanic where players take turns selecting actions from a shared pool.\", \"inferred_stereotype\": \"kind\"},",
    "input: Sorrow",
    "output: {\"name\": \"Sorrow\", \"description\": \"A feeling of deep distress caused by loss, disappointment, or other misfortune suffered by oneself or others.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Small talk",
    "output: {\"name\": \"Small talk\", \"description\": \"Polite conversation about unimportant or uncontroversial matters, especially as engaged in on social occasions.\", \"inferred_stereotype\": \"kind\"},",
    "input: Variable Phase Order",
    "output: {\"name\": \"Variable Phase Order\", \"description\": \"A game mechanic where the order of phases in a game can change.\", \"inferred_stereotype\": \"kind\"},",
    "input: Draft",
    "output: {\"name\": \"Draft\", \"description\": \"A preliminary version ofa piece of writing.\", \"inferred_stereotype\": \"kind\"},",
    "input: Storytelling",
    "output: {\"name\": \"Storytelling\", \"description\": \"The interactive or collaborative art of telling stories.\", \"inferred_stereotype\": \"kind\"},",
    "input: Take That",
    "output: {\"name\": \"Take That\", \"description\": \"A game mechanic where players can directly harm or hinder other players.\", \"inferred_stereotype\": \"kind\"},",
    "input: Color Appreciation",
    "output: {\"name\": \"Color Appreciation\", \"description\": \"The ability to perceive and appreciate colors.\", \"inferred_stereotype\": \"kind\"},",
    "input: Partnership",
    "output: {\"name\": \"Partnership\", \"description\": \"The state of being a partner or partners.\", \"inferred_stereotype\": \"kind\"},",
    "input: Exasperation",
    "output: {\"name\": \"Exasperation\", \"description\": \"A feeling of intense irritation or annoyance.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Tile",
    "output: {\"name\": \"Tile\", \"description\": \"A thin, flat piece of baked clay, stone, or concrete, typically square or rectangular in shape, used in building, especially for covering roofs, floors, or walls.\", \"inferred_stereotype\": \"kind\"},",
    "input: Resource Management",
    "output: {\"name\": \"Resource Management\", \"description\": \"The process of managing resources in a game.\", \"inferred_stereotype\": \"kind\"},",
    "input: Grouping",
    "output: {\"name\": \"Grouping\", \"description\": \"The action of putting people or things into groups.\", \"inferred_stereotype\": \"kind\"},",
    "input: Naches",
    "output: {\"name\": \"Naches\", \"description\": \"Pride and joy in one's children or grandchildren.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Hopelessness",
    "output: {\"name\": \"Hopelessness\", \"description\": \"A feeling or state of despair; lack of hope.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Compassion",
    "output: {\"name\": \"Compassion\", \"description\": \"Sympathetic pity and concern for the sufferings or misfortunes of others.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Victory Points",
    "output: {\"name\": \"Victory Points\", \"description\": \"A unit of measurement used in some games to determine the winner.\", \"inferred_stereotype\": \"kind\"},",
    "input: Grief",
    "output: {\"name\": \"Grief\", \"description\": \"Deep sorrow, especially that caused by someone's death.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Dynamics",
    "output: {\"name\": \"Dynamics\", \"description\": \"The forces or properties that stimulate growth, development, or change within a system or process.\", \"inferred_stereotype\": \"kind\"},",
    "input: Forcefull interpretation",
    "output: {\"name\": \"Forcefull interpretation\", \"description\": \"The act of interpreting something in a forceful or assertive manner.\", \"inferred_stereotype\": \"kind\"},",
    "input: Greed",
    "output: {\"name\": \"Greed\", \"description\": \"Intense and selfish desire for something, especially wealth, power, or food.\", \"inferred_stereotype\": \"kind\"},",
    "input: Dislike",
    "output: {\"name\": \"Dislike\", \"description\": \"A feeling of aversion or disapproval.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Paper And Pencil",
    "output: {\"name\": \"Paper And Pencil\", \"description\": \"A game played with paper and pencil.\", \"inferred_stereotype\": \"kind\"},",
    "input: Deck",
    "output: {\"name\": \"Deck\", \"description\": \"A pack of playing cards.\", \"inferred_stereotype\": \"kind\"},",
    "input: Peace",
    "output: {\"name\": \"Peace\", \"description\": \"Freedom from disturbance; tranquility.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Ecstasy",
    "output: {\"name\": \"Ecstasy\", \"description\": \"An overwhelming feeling of great happiness or joyful excitement.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Revulsion",
    "output: {\"name\": \"Revulsion\", \"description\": \"A sense of disgust and loathing.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Resource extinction",
    "output: {\"name\": \"Resource extinction\", \"description\": \"The depletion of a resource to the point where it is no longer available.\", \"inferred_stereotype\": \"kind\"},",
    "input: Areas",
    "output: {\"name\": \"Areas\", \"description\": \"A region or part of a town, a country, or the world.\", \"inferred_stereotype\": \"kind\"},",
    "input: Loathing",
    "output: {\"name\": \"Loathing\", \"description\": \"A feeling of intense dislike or disgust; detestation.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Press Your Luck",
    "output: {\"name\": \"Press Your Luck\", \"description\": \"A game mechanic where players can risk their current winnings for the chance to win more.\", \"inferred_stereotype\": \"kind\"},",
    "input: Frustration",
    "output: {\"name\": \"Frustration\", \"description\": \"The feeling of being upset or annoyed, especially because of inability to change or achieve something.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Reduce options",
    "output: {\"name\": \"Reduce options\", \"description\": \"The act of reducing the number of options available.\", \"inferred_stereotype\": \"kind\"},",
    "input: Random Draw",
    "output: {\"name\": \"Random Draw\", \"description\": \"A game mechanic where an outcome is determined by a random selection.\", \"inferred_stereotype\": \"kind\"},",
    "input: Helplessness",
    "output: {\"name\": \"Helplessness\", \"description\": \"The inability to defend oneself or to act effectively.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Argumentativeness",
    "output: {\"name\": \"Argumentativeness\", \"description\": \"The tendency to argue or engage in disputes.\", \"inferred_stereotype\": \"subkind\"},",
    "input: Mechanics",
    "output: {\"name\": \"Mechanics\", \"description\": \"The branch of physics concerned with the motion of bodies under the action of given forces.\", \"inferred_stereotype\": \"kind\"},",
    "input: Indirect effect",
    "output: {\"name\": \"Indirect effect\", \"description\": \"An effect that is not caused directly by an action, but rather through an intermediary.\", \"inferred_stereotype\": \"kind\"},",
    "input: Modular Board",
    "output: {\"name\": \"Modular Board\", \"description\": \"A game board that is made up of smaller, interchangeable modules.\", \"inferred_stereotype\": \"kind\"}",
])

generate_instructions = """
Task: Ontological Modeling with OntoUML Stereotypes

Input:

You will receive a list of elements delimited by triple backticks (```). Each element will consist of a single word or phrase representing a concept within a domain.

Steps:

Parse Input: Read the list of elements, carefully noting each name.
Research and Define: For each element:
If you are familiar with the concept, write a concise description that accurately reflects its meaning within the context of the domain.
If you are unsure, research the concept to gain a clear understanding before writing a description.
Infer Stereotype: Based on your description and your knowledge of OntoUML stereotypes, determine the most suitable stereotype for the element.
Prioritize the most specific stereotype that accurately reflects the element's nature.
Output JSON: Generate a JSON array where each object represents an element and contains the following keys:
name: The element's name.
description: The description you wrote for the element.
inferred_stereotype: The inferred OntoUML stereotype.
OntoUML Stereotypes:

Remember that you must use these specific stereotypes:

Classes: kind, collective, quantity, quality, mode, relator, subkind, phase, role, historicalRole, historicalRoleMixin, category, phaseMixin, roleMixin, mixin, type, event, situation, process
Relations: (not used in this task, but included for completeness) material, derivation, comparative, mediation, characterization, externalDependence, componentOf, memberOf, subCollectionOf, subQuantityOf, instantiation, termination, participational, participation, historicalDependence, creation, manifestation, bringsAbout, triggers, composition, aggregation, inherence, value, formal
Example Input:

Book
Author
Genre 
Example Output:

[
    {"name": "Book", "description": "A written or printed work consisting of pages.", "inferred_stereotype": "kind"},
    {"name": "Author", "description": "A person who writes books or articles.", "inferred_stereotype": "role"},
    {"name": "Genre", "description": "A category of artistic composition, characterized by similarities in form, style, or subject matter.", "inferred_stereotype": "subkind"}
]
Additional Notes:

Thorough Research: Ensure your descriptions are accurate and relevant to the context of the domain.
Justification: If multiple stereotypes seem plausible, briefly explain your choice in a comment within the JSON object.
No Guessing: If you cannot confidently infer a stereotype, leave the inferred_stereotype key blank for that element and provide a brief explanation as to why.
"""

def get_messages(prompt):
    messages = [
        {"role": "system", "content": f'{ufo_instructions}\n{stereotypes}\n{generate_instructions}'},
        {"role": "user", "content": f"input: ### {prompt} ###"}
    ]
    return messages